# Generated by Django 5.1.1 on 2024-09-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='brand_choices',
            field=models.CharField(blank=True, choices=[('mac os ', 'mac OS'), ('dell', 'dell'), ('hp', 'hp'), ('lenovo', 'lenovo'), ('asus', 'asus')], max_length=50, null=True),
        ),
    ]
